### PR TITLE
ParseCpsl - 1) replace System.err.println to log.error; 2) "duplicate binding name" set to warn logging level

### PR DESCRIPTION
**Pull request by kostyantyn-lexicallabs**
ParseCpsl - 1) replace System.err.println to log.error; 2) "duplicate binding name" set to warn logging level

1. It is good to be able to manage logging via logback settings instead of just printing to System.err.
2. "duplicate binding name" is not an error, actually. We have lots of complex rules that work perfectly but we have lots of these messages in the log that we would like to turn off via logback settings

### CODE REVIEW

**Comment by greenwoodma** [comment]
Happy to change from using `System.err` to using the proper logger. I'm not so convinced by the second change though.

Whilst the rules will still run if there are multiple bindings with the same name I'm not sure you'll actually be able to access the bindings correctly on the RHS. The problem is that after a binding name has been seen once, and stored along with the pattern segment it matches, any further uses of the same binding name are simply thrown away. This means that if your rule matches anything other than the first use of the binding name, the resulting binding set on the RHS is likely to be empty. I need to go and actually write a test for this to be 100% certain, but looking at the code I'm fairly confident this will be the case. @ianroberts do you agree with this or have I missed something obvious?

**Comment by greenwoodma** [comment]
Okay, having tried to test this more thoroughly, I'm tending towards saying it's still an error not a warning but it's not quite as bad as I thought it might be.

Firstly, I'm not sure why the `gate.jape.LeftHandSide` class bothers to store the binding label in a map against the section of rule, as it's only ever used in the `toString` method which I can't imagine being used very often.

This does mean that if you use the same label more than once that yes the rule will match but you still get some odd behaviour. Let's assume you use the same label twice. If the rule is such that only one of those sections can be hit (i.e. they are both sides of an OR) then yes you will get the correct annotations in the binding set, although you won't be able to tell on the RHS which section of the rule matched (which you would if you used separate labels as one would be empty). I don't particularly like that but I can see why it might be useful to reduce code on the RHS, although I'd probably make use of `bindings.getOrDefault` instead if you wanted simple code.

On the other hand if both labelled sections can be matched at the same time, then the bindings set ends up containing all the annotations from both sections of the rule. This seems almost guaranteed to be confusing, especially if you didn't intend to use the same label (i.e. a typo or mistake put you in this situation).

I'd still be tempted to label this as an error rather than a warning, especially as we always stress that binding labels should be unique on the LHS when teaching JAPE. @ianroberts do you agree with that or do you think dropping it to a warning would be more appropriate, and do any of the other log messages need their level changing?

**Comment by ianroberts** [comment]
I'm happy with the switch to a proper logger, though given all these `System.err` things are really warnings rather than errors (they just result in the relevant thing being ignored or treated as zero rather than actually failing the parse) I'd be inclined to make them all `log.warn` rather than `.error`, including the duplicate binding label one.  In fact there may be a case for dropping "duplicate binding" all the way down to info, since there are plenty of valid reasons why you might want to use the same label in more than one place

- mutually-exclusive branches of the same rule that all look for the same thing in different contexts
- a rule looking for a sequence of things and you want to for-each over the individual things on the RHS

  ```
  (
    ({Thing}):thing
    (
      ({Token.string == ","} | {Token.string == "and"}
      ({Thing}):thing
    )*
  ):allTheThings
  -->
  :allTheThings.Sequence = {}
  :thing{
    for(Annotation thing : thingAnnots) { ... }
  }
  ```

In that last example in particular there's very little difference between this case and the case without the initial `({Thing}):thing`, which still ends up assigning multiple discontinuous annotations to the `thing` binding but wouldn't be flagged as a duplicate by the parser.

**Comment by greenwoodma** [comment]
Fair enough, that last example has me convinced it should be info. I'm tempted to say that `unlisted annotation type` should still be an error as it is more serious than the others as it means that the rule will never match (assuming it's not only used in an optional section of a rule)

**Pull request merged**
